language: java
before_script:
  - unset GEM_PATH GEM_HOME IRBRC
  - "export PATH=`pwd`/bin:$PATH"
# disable cext
env: JAVA_OPTS="-server -Djruby.cext.enabled=false"
jdk:
  - oraclejdk7
#  - openjdk6
script: "ant test-extended"
install: /bin/true
notifications:
  irc:
    channels:
      - "irc.freenode.org#jruby"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})" 
